from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Associate',
    'Client',
    'Product',
    'LineItem',
    'Order',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Associate': {
        'audited_orders': 'Order',
        'sales_clients': 'Client',
        'sales_orders': 'Order',
        'tech_clients': 'Client',
        'tech_orders': 'Order',
    },
    'Client': {
        'orders': 'Order',
        'sales_associates': 'Associate',
        'tech_associates': 'Associate',
    },
    'Product': {
        'lineitems': 'LineItem',
    },
    'LineItem': {
        'product': 'Product',
        'orders': 'Order',
    },
    'Order': {
        'audited_by': 'Associate',
        'client': 'Client',
        'sales_associates': 'Associate',
        'tech_associates': 'Associate',
        'lineitems': 'LineItem',
    },
}

# fmt: on